// Generated by https://quicktype.io

export interface MatchItem {
  platformId: string;
  gameId:     number;
  champion:   number;
  queue:      number;
  season:     number;
  timestamp:  number;
  role:       string;
  lane:       string;
}
